import {
  Affix,
  Avatar,
  BackTop,
  Breadcrumb,
  Button,
  Card,
  Col,
  DatePicker,
  Divider,
  Dropdown,
  Empty,
  Form,
  FormItem,
  Input,
  InputNumber,
  InputPassword,
  Layout,
  LayoutContent,
  LayoutHeader,
  LayoutSider,
  Menu,
  MenuItem,
  Modal,
  PageHeader,
  Radio,
  RadioGroup,
  Row,
  Select,
  Space,
  Spin,
  Step,
  Steps,
  SubMenu,
  Table,
  TableSummary,
  TableSummaryCell,
  TableSummaryRow,
  Textarea,
  Timeline,
  TimelineItem,
  Tooltip,
  TypographyTitle,
  Upload,
} from 'ant-design-vue';

export default (app) => {
  app
    .use(Affix)
    .use(Avatar)
    .use(BackTop)
    .use(Breadcrumb)
    .use(Button)
    .use(Card)
    .use(Col)
    .use(DatePicker)
    .use(Divider)
    .use(Dropdown)
    .use(Empty)
    .use(Form)
    .use(FormItem)
    .use(Input)
    .use(InputNumber)
    .use(InputPassword)
    .use(Layout)
    .use(LayoutContent)
    .use(LayoutHeader)
    .use(LayoutSider)
    .use(Menu)
    .use(MenuItem)
    .use(Modal)
    .use(PageHeader)
    .use(Radio)
    .use(RadioGroup)
    .use(Row)
    .use(Select)
    .use(Space)
    .use(Spin)
    .use(Step)
    .use(Steps)
    .use(SubMenu)
    .use(Table)
    .use(TableSummary)
    .use(TableSummaryCell)
    .use(TableSummaryRow)
    .use(Textarea)
    .use(Timeline)
    .use(TimelineItem)
    .use(Tooltip)
    .use(TypographyTitle)
    .use(Upload);

  return app;
};
